import parent as p
import child as c
# me=p.Person("Yoorae")
# me.greeting()
# you=p.Person("Kim")
# you.greeting()
# 하율=c.Female("Hayul")
# 하율.greeting()
# 승욱=c.male("Seungwook")
# 승욱.greeting()
연필=c.pencil("pencil",1000)
연필.how_much()
연필.how_much_dozen()
지우개=c.eraser("eraser",500)
지우개.how_much()
지우개.how_much_pack()